apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteragents.cluster.appdynamics.com
spec:
  group: cluster.appdynamics.com
  names:
    kind: Clusteragent
    listKind: ClusteragentList
    plural: clusteragents
    singular: clusteragent
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infravizs.cluster.appdynamics.com
spec:
  group: cluster.appdynamics.com
  names:
    kind: InfraViz
    listKind: InfraVizList
    plural: infravizs
    singular: infraviz
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-operator
  namespace: appdynamics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appdynamics-operator
  namespace: appdynamics
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - endpoints
      - persistentvolumeclaims
      - resourcequotas
      - nodes
      - events
      - namespaces
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
    verbs:
      - "*"
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - cluster.appdynamics.com
    resources:
      - clusteragents
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.appdynamics.com
    resources:
      - clusteragents/finalizers
    verbs:
      - update
  - apiGroups:
      - cluster.appdynamics.com
    resources:
      - clusteragents/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cluster.appdynamics.com
    resources:
      - infravizs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.appdynamics.com
    resources:
      - infravizs/finalizers
    verbs:
      - update
  - apiGroups:
      - cluster.appdynamics.com
    resources:
      - infravizs/status
    verbs:
      - get
      - patch
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-operator
  namespace: appdynamics
subjects:
  - kind: ServiceAccount
    name: appdynamics-operator
    namespace: appdynamics
roleRef:
  kind: Role
  name: appdynamics-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdynamics-operator
  namespace: appdynamics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appdynamics-operator
  template:
    metadata:
      labels:
        name: appdynamics-operator
    spec:
      serviceAccountName: appdynamics-operator
      containers:
        - name: appdynamics-operator
          image: docker.io/appdynamics/cluster-agent-operator:22.7.0
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - appdynamics-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "appdynamics-operator"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-cluster-agent
  namespace: appdynamics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdynamics-cluster-agent
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - endpoints
      - persistentvolumeclaims
      - resourcequotas
      - nodes
      - events
      - namespaces
      - services
      - configmaps
      - secrets
      - replicationcontrollers
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdynamics-cluster-agent-instrumentation
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - secrets
      - configmaps
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - update
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-cluster-agent
subjects:
  - kind: ServiceAccount
    name: appdynamics-cluster-agent
    namespace: appdynamics
roleRef:
  kind: ClusterRole
  name: appdynamics-cluster-agent
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-cluster-agent-instrumentation
subjects:
  - kind: ServiceAccount
    name: appdynamics-cluster-agent
    namespace: appdynamics
roleRef:
  kind: ClusterRole
  name: appdynamics-cluster-agent-instrumentation
  apiGroup: rbac.authorization.k8s.io
