apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
---
apiVersion: cluster.appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "http://<appdynamics-controller-host>:8080"
  image: "<your-docker-registry>/appdynamics/machine-agent:latest"
  account: "<account-name>"
  enableContainerHostId: true
