{{ $mode := .Values.deploymentMode }}
{{ if or (eq $mode "PRIMARY") (eq $mode "NAMESPACED") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operatorServiceAccount }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: appdynamics-operator
  apiGroup: rbac.authorization.k8s.io
{{ end -}}
