{{ if .Values.installClusterAgent -}}
{{ $mode := .Values.deploymentMode -}}
{{ if and .Values.createServiceAccount (or (eq $mode "PRIMARY") (eq $mode "NAMESPACED")) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agentServiceAccount }}
  namespace: {{ .Release.Namespace }}
{{ end -}}
{{ end -}}