{{ $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-agent-proxy-secret") }}
{{ $annotations := dict "temp" "temp" }}
{{ if $secret }}
  {{ $annotations = $secret.metadata.annotations }}
{{ end }}
{{ if or (not ($secret)) (get $annotations "appdynamics.helm.charts/created-by") }}
{{ $namespace := .Release.Namespace }}
{{ with .Values -}}
{{ $mode := .deploymentMode -}}
{{ if or (eq $mode "PRIMARY") (eq $mode "NAMESPACED") -}}
{{ if .controllerInfo.authenticateProxy -}}
{{ if not .controllerInfo.proxyUrl -}}
{{ fail "Proxy url is requried to authenticate proxy!" -}}
{{ end -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-proxy-secret
  namespace: {{ $namespace }}
  annotations:
    appdynamics.helm.charts/created-by: cluster-agent-helm-chart
type: Opaque
data:
  proxy-password: {{ include "sensitiveData" (dict "data" .controllerInfo.proxyPassword "message" "Proxy password is required!") }}
{{ end -}}
{{ end -}}
{{ end -}}
{{ end -}}